version: 2
jobs:
  cargo_fetch:
    docker:
      - image: inputoutput/rust:stable
    working_directory: /home/circleci/project
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - restore_cache:
          keys:
            - cargo-v3-{{ checksum "Cargo.toml" }}-{{ checksum "Cargo.lock" }}
            - cargo-v3-{{ checksum "Cargo.toml" }}
            - cargo-v3-
      - run: cargo fetch
      - save_cache:
          key: cargo-v3-{{ checksum "Cargo.toml" }}-{{ checksum "Cargo.lock" }}
          paths:
            - /usr/local/cargo/registry
            - /usr/local/cargo/git

  cargo_audit:
    docker:
      - image: inputoutput/rust:stable
    working_directory: /home/circleci/project
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - restore_cache:
          keys:
            - cargo-v3-{{ checksum "Cargo.toml" }}-{{ checksum "Cargo.lock" }}
      - restore_cache:
          keys:
            - cargo-advisory-db-v1
      - run:
          name: Print Cargo Audit Version
          command: cargo audit --version
      - run:
          name: Check Cargo Audit
          command: cargo audit
      - save_cache:
          key: cargo-advisory-db-v1
          paths:
            - /usr/local/cargo/advisory-db

  rustfmt:
    docker:
      - image: inputoutput/rust:stable
    working_directory: /home/circleci/project
    steps:
      - checkout
      - run:
          name: Print version information
          command: cargo fmt -- --version
      - run:
          name: Check rustfmt
          command: cargo fmt -- --check

  test_debug:
    docker:
      - image: inputoutput/rust:stable
    environment:
      CARGO_INCREMENTAL: 0
    working_directory: /home/circleci/project
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - restore_cache:
          keys:
            - cargo-v3-{{ checksum "Cargo.toml" }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Print version information
          command: rustc --version; cargo --version
      - run:
          name: Build binaries
          command: cargo build -p jormungandr -p jcli --offline --verbose --frozen
      - run:
          name: Build tests
          command: cargo build --tests --offline --verbose --frozen
      - run:
          name: Test
          environment:
            RUST_BACKTRACE: 1
          command: cargo test --offline --verbose --frozen --tests

  test_doc:
    docker:
      - image: inputoutput/rust:stable
    environment:
      CARGO_INCREMENTAL: 0
    working_directory: /home/circleci/project
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - restore_cache:
          keys:
            - cargo-v3-{{ checksum "Cargo.toml" }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Print version information
          command: rustc --version; cargo --version
      - run:
          name: Test
          environment:
            RUST_BACKTRACE: 1
          command: cargo test --offline --verbose --frozen --doc -- --test-threads=1

  test_release:
    docker:
      - image: inputoutput/rust:stable
    working_directory: /home/circleci/project
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - restore_cache:
          keys:
            - cargo-v3-{{ checksum "Cargo.toml" }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Print version information
          command: rustc --version; cargo --version
      - run:
          name: Build binaries
          command: cargo build -p jormungandr -p jcli --release --offline --verbose --frozen
      - run:
          name: Build tests
          command: cargo build --tests --release --offline --verbose --frozen
      - run:
          name: Test
          command: cargo test --release --offline --verbose --tests

  test_beta:
    docker:
      - image: instrumentisto/rust:beta
    environment:
      CARGO_INCREMENTAL: 0
    working_directory: /home/circleci/project
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - restore_cache:
          keys:
            - cargo-v3-{{ checksum "Cargo.toml" }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Print version information
          command: rustc --version; cargo --version
      - run:
          name: Build binaries
          command: cargo build -p jormungandr -p jcli --offline --verbose --frozen
      - run:
          name: Build tests
          command: cargo build --tests --offline --verbose --frozen
      - run:
          name: Test
          environment:
            RUST_BACKTRACE: 1
          command: cargo test --offline --verbose --tests

workflows:
  version: 2
  test_all:
    jobs:
      - cargo_fetch
      - rustfmt
      # Temporarily disabled, vulnerable dependencies are pending update
      #- cargo_audit:
      #    requires:
      #      - cargo_fetch
      - test_debug:
          requires:
            - rustfmt
            - cargo_fetch
      - test_doc:
          requires:
            - rustfmt
            - cargo_fetch
      - test_release:
          requires:
            - rustfmt
            - cargo_fetch
      - test_beta:
          requires:
            - rustfmt
            - cargo_fetch
